// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --include-generated-funcs
// RUN: %cheri_purecap_cc1 %s -disable-O0-optnone -emit-llvm -o - \
// RUN:   | opt -S -mem2reg | FileCheck %s --check-prefix=PURECAP
// RUN: %cheri_cc1 %s -disable-O0-optnone -emit-llvm -o - \
// RUN:   | opt -S -mem2reg | FileCheck %s --check-prefix=HYBRID


struct foo {
  struct bar {
    bar(const bar&);
    float b1;
    float b2;
  } a1;
  foo(const foo&);
  float a2;
  float a3;
  float a4;
  float a5;
  void * __capability a6;
};

foo::foo(const foo&) = default;

// Also check the case where the first field (a2) is a bitfield.
struct baz {
  struct biz {
    biz(const biz&);
    float b1;
    float b2;
  } a1;
  baz(const baz&);
  unsigned int a2 : 24;
  float a3;
  float a4;
  float a5;
  void * __capability a6;
};

baz::baz(const baz&) = default;
// PURECAP-LABEL: @_ZN3fooC2ERKS_(
// PURECAP-NEXT:  entry:
// PURECAP-NEXT:    [[A1:%.*]] = getelementptr inbounds [[STRUCT_FOO:%.*]], ptr addrspace(200) [[THIS:%.*]], i32 0, i32 0
// PURECAP-NEXT:    [[A12:%.*]] = getelementptr inbounds [[STRUCT_FOO]], ptr addrspace(200) [[TMP0:%.*]], i32 0, i32 0
// PURECAP-NEXT:    call void @_ZN3foo3barC1ERKS0_(ptr addrspace(200) noundef nonnull align 4 dereferenceable(8) [[A1]], ptr addrspace(200) noundef nonnull align 4 dereferenceable(8) [[A12]])
// PURECAP-NEXT:    [[A2:%.*]] = getelementptr inbounds [[STRUCT_FOO]], ptr addrspace(200) [[THIS]], i32 0, i32 1
// PURECAP-NEXT:    [[A23:%.*]] = getelementptr inbounds [[STRUCT_FOO]], ptr addrspace(200) [[TMP0]], i32 0, i32 1
// PURECAP-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) align 8 [[A2]], ptr addrspace(200) align 8 [[A23]], i64 8, i1 false) #[[ATTR3:[0-9]+]]
// PURECAP-NEXT:    [[TMP1:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[A2]], i64 8
// PURECAP-NEXT:    [[TMP2:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[A23]], i64 8
// PURECAP-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) align 16 [[TMP1]], ptr addrspace(200) align 16 [[TMP2]], i64 32, i1 false)
// PURECAP-NEXT:    ret void
//
//
// PURECAP-LABEL: @_ZN3fooC1ERKS_(
// PURECAP-NEXT:  entry:
// PURECAP-NEXT:    call void @_ZN3fooC2ERKS_(ptr addrspace(200) noundef nonnull align 16 dereferenceable(48) [[THIS:%.*]], ptr addrspace(200) noundef nonnull align 16 dereferenceable(48) [[TMP0:%.*]])
// PURECAP-NEXT:    ret void
//
//
// PURECAP-LABEL: @_ZN3bazC2ERKS_(
// PURECAP-NEXT:  entry:
// PURECAP-NEXT:    [[A1:%.*]] = getelementptr inbounds [[STRUCT_BAZ:%.*]], ptr addrspace(200) [[THIS:%.*]], i32 0, i32 0
// PURECAP-NEXT:    [[A12:%.*]] = getelementptr inbounds [[STRUCT_BAZ]], ptr addrspace(200) [[TMP0:%.*]], i32 0, i32 0
// PURECAP-NEXT:    call void @_ZN3baz3bizC1ERKS0_(ptr addrspace(200) noundef nonnull align 4 dereferenceable(8) [[A1]], ptr addrspace(200) noundef nonnull align 4 dereferenceable(8) [[A12]])
// PURECAP-NEXT:    [[A2:%.*]] = getelementptr inbounds [[STRUCT_BAZ]], ptr addrspace(200) [[THIS]], i32 0, i32 1
// PURECAP-NEXT:    [[A23:%.*]] = getelementptr inbounds [[STRUCT_BAZ]], ptr addrspace(200) [[TMP0]], i32 0, i32 1
// PURECAP-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) align 8 [[A2]], ptr addrspace(200) align 8 [[A23]], i64 8, i1 false) #[[ATTR3]]
// PURECAP-NEXT:    [[TMP1:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[A2]], i64 8
// PURECAP-NEXT:    [[TMP2:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[A23]], i64 8
// PURECAP-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) align 16 [[TMP1]], ptr addrspace(200) align 16 [[TMP2]], i64 32, i1 false)
// PURECAP-NEXT:    ret void
//
//
// PURECAP-LABEL: @_ZN3bazC1ERKS_(
// PURECAP-NEXT:  entry:
// PURECAP-NEXT:    call void @_ZN3bazC2ERKS_(ptr addrspace(200) noundef nonnull align 16 dereferenceable(48) [[THIS:%.*]], ptr addrspace(200) noundef nonnull align 16 dereferenceable(48) [[TMP0:%.*]])
// PURECAP-NEXT:    ret void
//
//
// HYBRID-LABEL: @_ZN3fooC2ERKS_(
// HYBRID-NEXT:  entry:
// HYBRID-NEXT:    [[A1:%.*]] = getelementptr inbounds [[STRUCT_FOO:%.*]], ptr [[THIS:%.*]], i32 0, i32 0
// HYBRID-NEXT:    [[A12:%.*]] = getelementptr inbounds [[STRUCT_FOO]], ptr [[TMP0:%.*]], i32 0, i32 0
// HYBRID-NEXT:    call void @_ZN3foo3barC1ERKS0_(ptr noundef nonnull align 4 dereferenceable(8) [[A1]], ptr noundef nonnull align 4 dereferenceable(8) [[A12]])
// HYBRID-NEXT:    [[A2:%.*]] = getelementptr inbounds [[STRUCT_FOO]], ptr [[THIS]], i32 0, i32 1
// HYBRID-NEXT:    [[A23:%.*]] = getelementptr inbounds [[STRUCT_FOO]], ptr [[TMP0]], i32 0, i32 1
// HYBRID-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[A2]], ptr align 8 [[A23]], i64 8, i1 false) #[[ATTR3:[0-9]+]]
// HYBRID-NEXT:    [[TMP1:%.*]] = getelementptr inbounds i8, ptr [[A2]], i64 8
// HYBRID-NEXT:    [[TMP2:%.*]] = getelementptr inbounds i8, ptr [[A23]], i64 8
// HYBRID-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 16 [[TMP1]], ptr align 16 [[TMP2]], i64 32, i1 false)
// HYBRID-NEXT:    ret void
//
//
// HYBRID-LABEL: @_ZN3fooC1ERKS_(
// HYBRID-NEXT:  entry:
// HYBRID-NEXT:    call void @_ZN3fooC2ERKS_(ptr noundef nonnull align 16 dereferenceable(48) [[THIS:%.*]], ptr noundef nonnull align 16 dereferenceable(48) [[TMP0:%.*]])
// HYBRID-NEXT:    ret void
//
//
// HYBRID-LABEL: @_ZN3bazC2ERKS_(
// HYBRID-NEXT:  entry:
// HYBRID-NEXT:    [[A1:%.*]] = getelementptr inbounds [[STRUCT_BAZ:%.*]], ptr [[THIS:%.*]], i32 0, i32 0
// HYBRID-NEXT:    [[A12:%.*]] = getelementptr inbounds [[STRUCT_BAZ]], ptr [[TMP0:%.*]], i32 0, i32 0
// HYBRID-NEXT:    call void @_ZN3baz3bizC1ERKS0_(ptr noundef nonnull align 4 dereferenceable(8) [[A1]], ptr noundef nonnull align 4 dereferenceable(8) [[A12]])
// HYBRID-NEXT:    [[A2:%.*]] = getelementptr inbounds [[STRUCT_BAZ]], ptr [[THIS]], i32 0, i32 1
// HYBRID-NEXT:    [[A23:%.*]] = getelementptr inbounds [[STRUCT_BAZ]], ptr [[TMP0]], i32 0, i32 1
// HYBRID-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[A2]], ptr align 8 [[A23]], i64 8, i1 false) #[[ATTR3]]
// HYBRID-NEXT:    [[TMP1:%.*]] = getelementptr inbounds i8, ptr [[A2]], i64 8
// HYBRID-NEXT:    [[TMP2:%.*]] = getelementptr inbounds i8, ptr [[A23]], i64 8
// HYBRID-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 16 [[TMP1]], ptr align 16 [[TMP2]], i64 32, i1 false)
// HYBRID-NEXT:    ret void
//
//
// HYBRID-LABEL: @_ZN3bazC1ERKS_(
// HYBRID-NEXT:  entry:
// HYBRID-NEXT:    call void @_ZN3bazC2ERKS_(ptr noundef nonnull align 16 dereferenceable(48) [[THIS:%.*]], ptr noundef nonnull align 16 dereferenceable(48) [[TMP0:%.*]])
// HYBRID-NEXT:    ret void
//
