; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --force-update
;; NB: Morello LLVM prefers address subtraction over @llvm.cheri.cap.diff, so
;; test does not make sense here.
; RUN: %cheri_purecap_opt -instcombine -S < %s | FileCheck %s
target datalayout = "A200-P200-G200"

declare i64 @llvm.cheri.cap.address.get.i64(i8 addrspace(200)*) addrspace(200)

; C source code: return ((ptraddr_t)first - (ptraddr_t)second) / 16;
define i64 @cap_subtract_with_vaddr_cast(i8 addrspace(200)* %first, i8 addrspace(200)* %second) addrspace(200) {
; CHECK-LABEL: @cap_subtract_with_vaddr_cast(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call addrspace(200) i64 @llvm.cheri.cap.address.get.i64(i8 addrspace(200)* [[FIRST:%.*]])
; CHECK-NEXT:    [[TMP1:%.*]] = call addrspace(200) i64 @llvm.cheri.cap.address.get.i64(i8 addrspace(200)* [[SECOND:%.*]])
; CHECK-NEXT:    [[SUB:%.*]] = sub i64 [[TMP0]], [[TMP1]]
; CHECK-NEXT:    [[DIV1:%.*]] = lshr i64 [[SUB]], 4
; CHECK-NEXT:    ret i64 [[DIV1]]
;
entry:
  %0 = call i64 @llvm.cheri.cap.address.get.i64(i8 addrspace(200)* %first)
  %1 = call i64 @llvm.cheri.cap.address.get.i64(i8 addrspace(200)* %second)
  %sub = sub i64 %0, %1
  %div = udiv i64 %sub, 16
  ret i64 %div
}
