; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64 -mattr=+morello -verify-machineinstrs %s -o - | FileCheck %s

define void @cap_mode_w(i8 addrspace(200)* %0, i32* %1) {
; CHECK-LABEL: cap_mode_w:
; CHECK:       // %bb.0:
; CHECK-NEXT:    //APP
; CHECK-NEXT:    str w0, [x1]
; CHECK-NEXT:    //NO_APP
; CHECK-NEXT:    ret
  tail call void asm "str ${1:w}, $0", "=*m,C"(i32* elementtype(i32) %1, i8 addrspace(200)* %0)
  ret void
}

define void @cap_mode_w_zero(i32* %0) {
; CHECK-LABEL: cap_mode_w_zero:
; CHECK:       // %bb.0:
; CHECK-NEXT:    //APP
; CHECK-NEXT:    str wzr, [x0]
; CHECK-NEXT:    //NO_APP
; CHECK-NEXT:    ret
  tail call void asm "str ${1:w}, $0", "=*m,C"(i32* elementtype(i32) %0, i8 addrspace(200)* null)
  ret void
}

define void @cap_mode_x(i8 addrspace(200)* %0, i64* %1) {
; CHECK-LABEL: cap_mode_x:
; CHECK:       // %bb.0:
; CHECK-NEXT:    //APP
; CHECK-NEXT:    str x0, [x1]
; CHECK-NEXT:    //NO_APP
; CHECK-NEXT:    ret
  tail call void asm "str ${1:x}, $0", "=*m,C"(i64* elementtype(i64) %1, i8 addrspace(200)* %0)
  ret void
}

define void @cap_mode_x_zero(i64* %0) {
; CHECK-LABEL: cap_mode_x_zero:
; CHECK:       // %bb.0:
; CHECK-NEXT:    //APP
; CHECK-NEXT:    str xzr, [x0]
; CHECK-NEXT:    //NO_APP
; CHECK-NEXT:    ret
  tail call void asm "str ${1:x}, $0", "=*m,C"(i64* elementtype(i64) %0, i8 addrspace(200)* null)
  ret void
}
