// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --function-signature
// RUN: %clang_cc1 -triple aarch64-none-elf -target-feature +morello -target-feature +c64 -target-abi purecap -o - %s -S -emit-llvm | FileCheck %s

struct some_other_struct {
  void * ptr[1];
};

struct some_struct {
// CHECK-LABEL: define {{[^@]+}}@_ZN11some_struct6getterEv
// CHECK-SAME: (ptr addrspace(200) noundef nonnull align 16 dereferenceable(16) [[THIS:%.*]]) addrspace(200) #[[ATTR0:[0-9]+]] comdat align 2 {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca [[STRUCT_SOME_OTHER_STRUCT:%.*]], align 16, addrspace(200)
// CHECK-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// CHECK-NEXT:    store ptr addrspace(200) [[THIS]], ptr addrspace(200) [[THIS_ADDR]], align 16
// CHECK-NEXT:    [[THIS1:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[THIS_ADDR]], align 16
// CHECK-NEXT:    [[FIELD_:%.*]] = getelementptr inbounds [[STRUCT_SOME_STRUCT:%.*]], ptr addrspace(200) [[THIS1]], i32 0, i32 0
// CHECK-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) align 16 [[RETVAL]], ptr addrspace(200) align 16 [[FIELD_]], i64 16, i1 false)
// CHECK-NEXT:    [[COERCE_DIVE:%.*]] = getelementptr inbounds [[STRUCT_SOME_OTHER_STRUCT]], ptr addrspace(200) [[RETVAL]], i32 0, i32 0
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[COERCE_DIVE]], align 16
// CHECK-NEXT:    ret ptr addrspace(200) [[TMP0]]
//
  inline some_other_struct getter() { return field_; }
  some_other_struct field_;
} i;

extern void callee(some_other_struct a);
// UTC_ARGS: --disable
void caller() {
  callee(i.getter());
}
