// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -Wall -Werror -triple aarch64-none-elf -target-feature +c64 -target-abi purecap -disable-O0-optnone -emit-llvm -o - %s | opt -S -mem2reg | FileCheck %s

// CHECK-LABEL: @test_tp_char(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call ptr addrspace(200) @llvm.thread.pointer.p200()
// CHECK-NEXT:    ret ptr addrspace(200) [[TMP0]]
//
void *test_tp_char() {
  return __builtin_thread_pointer();
}

// CHECK-LABEL: @test_tp_int(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call ptr addrspace(200) @llvm.thread.pointer.p200()
// CHECK-NEXT:    ret ptr addrspace(200) [[TMP0]]
//
int *test_tp_int() {
  return __builtin_thread_pointer();
}
