// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple arm64-linux-gnu -target-feature +morello \
// RUN:    -target-feature +c64 -target-abi purecap \
// RUN:    -emit-llvm -o - -disable-O0-optnone %s | \
// RUN:  opt -S -mem2reg | \
// RUN:  FileCheck  %s

#include <stdarg.h>

struct hfa {
  float x;
  float y;
  float z;
};

struct comp {
  int *x;
  int y;
};


void call1(double, float);

// CHECK-LABEL: @callee_test_scalars(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ARGS:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// CHECK-NEXT:    call void @llvm.va_start.p200(ptr addrspace(200) [[ARGS]])
// CHECK-NEXT:    [[STACK:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[ARGS]], align 16
// CHECK-NEXT:    [[NEW_STACK:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[STACK]], i64 16
// CHECK-NEXT:    store ptr addrspace(200) [[NEW_STACK]], ptr addrspace(200) [[ARGS]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load double, ptr addrspace(200) [[STACK]], align 16
// CHECK-NEXT:    [[STACK1:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[ARGS]], align 16
// CHECK-NEXT:    [[NEW_STACK2:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[STACK1]], i64 16
// CHECK-NEXT:    store ptr addrspace(200) [[NEW_STACK2]], ptr addrspace(200) [[ARGS]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load float, ptr addrspace(200) [[STACK1]], align 16
// CHECK-NEXT:    call void @llvm.va_end.p200(ptr addrspace(200) [[ARGS]])
// CHECK-NEXT:    call void @call1(double noundef [[TMP0]], float noundef [[TMP1]])
// CHECK-NEXT:    ret void
//
void callee_test_scalars(int count, ...) {
    va_list args;
    va_start(args, count);
    double num0 = va_arg(args, double);
    float num1 = va_arg(args, float);
    va_end(args);
    return call1(num0, num1);
}

void call2(struct hfa, struct comp);

// CHECK-LABEL: @callee_test_aggregate(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ARGS:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// CHECK-NEXT:    [[NUM0:%.*]] = alloca [[STRUCT_HFA:%.*]], align 4, addrspace(200)
// CHECK-NEXT:    [[NUM1:%.*]] = alloca [[STRUCT_COMP:%.*]], align 16, addrspace(200)
// CHECK-NEXT:    call void @llvm.va_start.p200(ptr addrspace(200) [[ARGS]])
// CHECK-NEXT:    [[STACK:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[ARGS]], align 16
// CHECK-NEXT:    [[NEW_STACK:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[STACK]], i64 16
// CHECK-NEXT:    store ptr addrspace(200) [[NEW_STACK]], ptr addrspace(200) [[ARGS]], align 16
// CHECK-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) align 4 [[NUM0]], ptr addrspace(200) align 16 [[STACK]], i64 12, i1 false)
// CHECK-NEXT:    [[STACK1:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[ARGS]], align 16
// CHECK-NEXT:    [[NEW_STACK2:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[STACK1]], i64 16
// CHECK-NEXT:    store ptr addrspace(200) [[NEW_STACK2]], ptr addrspace(200) [[ARGS]], align 16
// CHECK-NEXT:    [[VAARG_ADDR:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[STACK1]], align 16
// CHECK-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) align 16 [[NUM1]], ptr addrspace(200) align 16 [[VAARG_ADDR]], i64 32, i1 false)
// CHECK-NEXT:    call void @llvm.va_end.p200(ptr addrspace(200) [[ARGS]])
// CHECK-NEXT:    [[TMP0:%.*]] = load [3 x float], ptr addrspace(200) [[NUM0]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = load { ptr addrspace(200), i64 }, ptr addrspace(200) [[NUM1]], align 16
// CHECK-NEXT:    call void @call2([3 x float] [[TMP0]], { ptr addrspace(200), i64 } [[TMP1]])
// CHECK-NEXT:    ret void
//
void callee_test_aggregate(int count, ...) {
    va_list args;
    va_start(args, count);
    struct hfa num0 = va_arg(args, struct hfa);
    struct comp num1 = va_arg(args, struct comp);
    va_end(args);
    return call2(num0, num1);
}

// CHECK-LABEL: @test_vacopy(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ARGS:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// CHECK-NEXT:    [[ARGS1:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// CHECK-NEXT:    call void @llvm.va_start.p200(ptr addrspace(200) [[ARGS]])
// CHECK-NEXT:    call void @llvm.va_copy.p200.p200(ptr addrspace(200) [[ARGS1]], ptr addrspace(200) [[ARGS]])
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[ARGS1]], align 16
// CHECK-NEXT:    ret ptr addrspace(200) [[TMP0]]
//
va_list test_vacopy(int count, ...) {
  va_list args;
  va_list args1;
  va_start(args, count);
  va_copy(args1, args);
  return args1;
}

struct empty {};

// CHECK-LABEL: @foo(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AP:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// CHECK-NEXT:    call void @llvm.va_start.p200(ptr addrspace(200) [[AP]])
// CHECK-NEXT:    [[STACK:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[AP]], align 16
// CHECK-NEXT:    [[STACK1:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[AP]], align 16
// CHECK-NEXT:    [[NEW_STACK:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[STACK1]], i64 16
// CHECK-NEXT:    store ptr addrspace(200) [[NEW_STACK]], ptr addrspace(200) [[AP]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr addrspace(200) [[STACK1]], align 16
// CHECK-NEXT:    ret i32 [[TMP0]]
//
int foo(int count, ...) {
  int ret;
  __builtin_va_list ap;
  __builtin_va_start (ap, count);
  __builtin_va_arg (ap, struct empty);
  ret = __builtin_va_arg (ap, int);
  return ret;
}
