// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple aarch64-none-elf -target-feature +morello -target-feature +c64 -disable-O0-optnone -target-abi purecap %s -S -emit-llvm -o - | opt -sroa -S | FileCheck %s
struct S1 {
  void *a;
  void *b;
};

void bar(struct S1 arg);

// CHECK-LABEL: @foo(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[LIST:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// CHECK-NEXT:    call void @llvm.va_start.p200(ptr addrspace(200) [[LIST]])
// CHECK-NEXT:    [[STACK:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[LIST]], align 16
// CHECK-NEXT:    [[NEW_STACK:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[STACK]], i64 16
// CHECK-NEXT:    store ptr addrspace(200) [[NEW_STACK]], ptr addrspace(200) [[LIST]], align 16
// CHECK-NEXT:    [[VAARG_ADDR:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[STACK]], align 16
// CHECK-NEXT:    [[ARG_SROA_0_0_COPYLOAD:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[VAARG_ADDR]], align 16
// CHECK-NEXT:    [[ARG_SROA_2_0_VAARG_ADDR_SROA_IDX:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[VAARG_ADDR]], i64 16
// CHECK-NEXT:    [[ARG_SROA_2_0_COPYLOAD:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[ARG_SROA_2_0_VAARG_ADDR_SROA_IDX]], align 16
// CHECK-NEXT:    [[DOTFCA_0_INSERT:%.*]] = insertvalue { ptr addrspace(200), ptr addrspace(200) } poison, ptr addrspace(200) [[ARG_SROA_0_0_COPYLOAD]], 0
// CHECK-NEXT:    [[DOTFCA_1_INSERT:%.*]] = insertvalue { ptr addrspace(200), ptr addrspace(200) } [[DOTFCA_0_INSERT]], ptr addrspace(200) [[ARG_SROA_2_0_COPYLOAD]], 1
// CHECK-NEXT:    call void @bar({ ptr addrspace(200), ptr addrspace(200) } [[DOTFCA_1_INSERT]])
// CHECK-NEXT:    call void @llvm.va_end.p200(ptr addrspace(200) [[LIST]])
// CHECK-NEXT:    ret void
//
void foo(int i, ...) {
  __builtin_va_list list;
  __builtin_va_start(list, i);
  struct S1 arg = __builtin_va_arg(list, struct S1);
  bar(arg);
  __builtin_va_end(list);
}

struct S2 {
  long x1;
  long x2;
  long x3;
  long x4;
};

void bat(struct S2 arg);

// CHECK-LABEL: @baz(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[LIST:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// CHECK-NEXT:    [[ARG:%.*]] = alloca [[STRUCT_S2:%.*]], align 8, addrspace(200)
// CHECK-NEXT:    [[BYVAL_TEMP:%.*]] = alloca [[STRUCT_S2]], align 8, addrspace(200)
// CHECK-NEXT:    call void @llvm.va_start.p200(ptr addrspace(200) [[LIST]])
// CHECK-NEXT:    [[STACK:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[LIST]], align 16
// CHECK-NEXT:    [[NEW_STACK:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[STACK]], i64 16
// CHECK-NEXT:    store ptr addrspace(200) [[NEW_STACK]], ptr addrspace(200) [[LIST]], align 16
// CHECK-NEXT:    [[VAARG_ADDR:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[STACK]], align 16
// CHECK-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) align 8 [[ARG]], ptr addrspace(200) align 8 [[VAARG_ADDR]], i64 32, i1 false)
// CHECK-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) align 8 [[BYVAL_TEMP]], ptr addrspace(200) align 8 [[ARG]], i64 32, i1 false)
// CHECK-NEXT:    call void @bat(ptr addrspace(200) noundef [[BYVAL_TEMP]])
// CHECK-NEXT:    call void @llvm.va_end.p200(ptr addrspace(200) [[LIST]])
// CHECK-NEXT:    ret void
//
void baz(int i, ...) {
  __builtin_va_list list;
  __builtin_va_start(list, i);
  struct S2 arg = __builtin_va_arg(list, struct S2);
  bat(arg);
  __builtin_va_end(list);
}
