// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple aarch64-none-elf -target-feature +morello -S -emit-llvm -o - %s | opt -S -mem2reg | FileCheck %s


void bar(__builtin_va_list *);
void baz(__builtin_va_list);


// CHECK-LABEL: @foo(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ARG:%.*]] = alloca [[STRUCT___VA_LIST:%.*]], align 8
// CHECK-NEXT:    [[BYVAL_TEMP:%.*]] = alloca [[STRUCT___VA_LIST]], align 8
// CHECK-NEXT:    call void @bar(ptr noundef [[ARG]])
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[BYVAL_TEMP]], ptr align 8 [[ARG]], i64 32, i1 false) #[[ATTR3:[0-9]+]]
// CHECK-NEXT:    call void @baz(ptr noundef [[BYVAL_TEMP]])
// CHECK-NEXT:    ret void
//
void foo() {
  __builtin_va_list arg;
  bar(&arg);
  baz(arg);
}

