// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple aarch64 -target-feature +morello -target-feature +c64 -target-abi purecap %s -O2 -emit-llvm -o - | FileCheck %s
struct S {
  int r[5];
};

struct S a;

extern void fn2(struct S);

// CHECK-LABEL: @fn1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[BYVAL_TEMP:%.*]] = alloca [[STRUCT_S:%.*]], align 4, addrspace(200)
// CHECK-NEXT:    call void @llvm.lifetime.start.p200(i64 20, ptr addrspace(200) nonnull [[BYVAL_TEMP]]) #[[ATTR4:[0-9]+]]
// CHECK-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) noundef nonnull align 4 dereferenceable(20) [[BYVAL_TEMP]], ptr addrspace(200) noundef nonnull align 4 dereferenceable(20) @a, i64 20, i1 false), !tbaa.struct !2
// CHECK-NEXT:    call void @fn2(ptr addrspace(200) noundef nonnull [[BYVAL_TEMP]]) #[[ATTR4]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p200(i64 20, ptr addrspace(200) nonnull [[BYVAL_TEMP]]) #[[ATTR4]]
// CHECK-NEXT:    ret void
//
void fn1() {
  fn2(a);
}
