// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang %s -O0 -target aarch64-none-elf -march=morello -mabi=purecap -o - -S -emit-llvm | FileCheck %s
typedef void(*fn)();

extern void foo();

// CHECK-LABEL: @getFunctionPointer(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret ptr addrspace(200) @foo
//
fn getFunctionPointer() {
  return foo;

}
