// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple aarch64 -target-feature +morello -target-feature +c64 -target-abi purecap %s -emit-llvm -o - | FileCheck %s

typedef void(*fn)();

extern void foo();

// CHECK-LABEL: @getFunctionPointer(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret ptr addrspace(200) @foo
//
fn getFunctionPointer() {
  return foo;

}
